--- #YAML:1.0
name:               Crypt-Smithy
version:            0.01
abstract:           Perl implementation of the 'Smithycode' cipher.
author:
    - Andreas Faafeng <aff@cpan.org>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
